services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/xoxod33p/ci-cd:latest
    container_name: ci-cd-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:80"
